Encapsulation is an important concept in object-oriented programming.
Encapsulation just means that some information is not available directly
from outside the encapsulating object, only through specially provided
accessor methods.  This sounds like a pretty good idea at first glance:
the _implementation_ of something is hidden, and is allowed to change
without breaking things, because people using this code aren't able to
poke around inside and count on details they've discovered, they have
to use the accessor methods.

== Properties

Here's a contrived example, a fragmentary class describing
a person, where we've only shown one piece of data, the age of the person:

[source,c++]
----
class Person
{
    int age;
public:
    Person() : age(0) { }

    int getAge() { return age; }
    void setAge(int x) { age = x; }
};
----

Here the access to the class variable `age` is private, but we've also
provided a pair of methods which give access to the value of age:
one to get it, called `getAge` and one to set it, called `setAge`.
Now if something a lot more complicated needs to happen later to `age`
you can update the getter/setter methods but it doesn't affect clients
using this code.  That's not actually an unreasonable expectation -
the age of a person isn't a good candidate for data that looks static -
every year on their birthday it changes.  So why not improve the class
by calculating the age from the current date and the person's birth date
when it's asked for?

A lot of developers don't like this kind of code; it does accomplish
a useful function if you need it, but because you can't necessarily
guess when you're going to need it, when you're writing in a language
like Java, and to a slightly lesser extent C++, you have to set up the
getter/setter methods for variables up front in anticipation you might
need them later - since the interface has a binary (ABI) nature, if you
didn't use getter/setter, and then add that, you've broken programs
depending on the older behavior.  This bloats the code and you never
know if it was needed, and adds no actual value to the code. That is,
you can easily go from 30 lines to 100 lines in your source file without
any new value being introduced.  Ah, but no problem, right?  My IDE just
built those for me...

There's an aesthetic concern regarding the syntax, also. A Person instance
includes that person's age, but we can't perform natural operations on
that age - if `a` is an instance, we can't access `a.age` or set it,
we have to use `a.getAge()` and `a.setAge()`.

The C# language at least improves on the syntax part of this:

[source,c#]
----
class Person
{
    private int age = 0;

    public int Age
    {
        get { return age; }
        set { age = value; }
    }
}
----

Because here `Age` behaves like it was a variable. Since C# considers
this a Property, and property access is though the getter/setter methods,
we can now directly access `a.Age` and it "looks like" a variable.

As a dynamic language, Python doesn't have the limitation of
static languages, in that you can change the implementation,
as long as you don't break it, without causing problems to clients.
Python has a property concept like C# - you can set up getter/setter
methods to data in a class. But you can defer implementing them until
you need them - you can have an instance variable which is directly
accessible, then if the implementation needs to do something more
complex than a simple variable, you can change to properties but
it will look the same to the client.

Here is a series of examples showing how properties work in Python.

Consider a Vector class that should include both an angle in
radians and an angle in degrees.  This provides an excuse to
use a getter method - we don't actually need to store both angles
in the instance, and indeed we don't even want to, because they're
reltated, and if someone updates one angle, we have a problem
because the other one needs to change in sync with it.  It's
nicer to store one, and generate the other one on demand - that
solves the sync problem.

Python provides the built-in `property()` function which sets
up a property given arguments which describe the methods which
implement the property behavior.  The arguments are in order
are the getter, setter, deleter, and docstring; they're
successively optional so if you pass only one argument to
property only a getter is assigned.

[source,python]
----
import math


class Vector(object):
    def __init__(self, angle_rad):
        self.set_angle_rad(angle_rad)

    def get_angle_rad(self):
        return math.radians(self._angle_deg)

    def set_angle_rad(self, angle_rad):
        self._angle_deg = math.degrees(angle_rad)

    angle = property(get_angle_rad, set_angle_rad)

    def get_angle_deg(self):
        return self._angle_deg

    def set_angle_deg(self, angle_deg):
        self._angle_deg = angle_deg

    angle_deg = property(get_angle_deg, set_angle_deg)
----

We can do some experiments with this class - in the first
two chunks of lines below we create an instance with a starting value
and print both angles, then change the angle and print
both again.  In the next chunk, we ask for some information
about the objects in question

[source,python]
----
v = Vector(2*math.pi)
print(v.angle)
print(v.angle_deg)

v.angle = math.pi
print(v.angle)
print(v.angle_deg)

print(Vector.angle, Vector.angle.getter, Vector.angle.setter)
print(Vector.angle_deg, Vector.angle_deg.getter, Vector.angle_deg.setter)
----

Here's the output of one run:

[source,python]
----
6.283185307179586
360.0
3.141592653589793
180.0
<property object at 0x7fab853b5f48>
  <built-in method getter of property object at 0x7fab853b5f48>
  <built-in method setter of property object at 0x7fab853b5f48>
<property object at 0x7fab7d3d9818>
  <built-in method getter of property object at 0x7fab7d3d9818>
  <built-in method setter of property object at 0x7fab7d3d9818>
----

Python provides decorators that have the same effect as
the the call to the `property` function. `@property` is used
for the getter, `@name.setter` for the setter and
`@name.deleter` for the deleter function which would be
the third argument to the `property` function if included.

[source,python]
----
import math


class Vector(object):
    def __init__(self, value):
        self.angle = value

    @property
    def angle(self):
        return math.radians(self._angle_deg)

    @angle.setter
    def angle(self, value):
        self._angle_deg = math.degrees(value)

    @property
    def angle_deg(self):
        return self._angle_deg

    @angle_deg.setter
    def angle_deg(self, value):
        self._angle_deg = value

v = Vector(2*math.pi)
print(v.angle)
print(v.angle_deg)

v.angle = math.pi
print(v.angle)
print(v.angle_deg)

print(Vector.angle, Vector.angle.getter, Vector.angle.setter)
print(Vector.angle_deg, Vector.angle_deg.getter, Vector.angle_deg.setter)
----

And the output of our experiments:

[source,python]
----
6.283185307179586
360.0
3.141592653589793
180.0
<property object at 0x7f7ba29b5818>
  <built-in method getter of property object at 0x7f7ba29b5818>
  <built-in method setter of property object at 0x7f7ba29b5818>
<property object at 0x7f7ba29b5868>
  <built-in method getter of property object at 0x7f7ba29b5868>
  <built-in method setter of property object at 0x7f7ba29b5868>
----

By decorating the pair of angle and angle_deg methods, we've
turned them into getter/setter methods, just like the call to the
`property()` function did, but this looks cleaner, you can
immediately see what each method is for rather than going hunting
for the `property` call.

I don't particularly like this code, though... we are using a
sort of hidden instance variable to actually hold the value
we do save, and we've served up getter/setter pairs for both
two public variables.  Except there is really no hidden data
in Python - starting a name with an underscore is a visual
hint that we don't really intend something to be public, but
that is all it is, a hint.  There is nothing special about
`_angle_deg`, it's just saved and restored like
an ordinary variable. So why not dispense with the property stuff
for this one and just make `angle_deg` an instance variable,
then we don't need `_angle_deg` at all. If we need to do something
"special" with `angle_deg` we can always turn it back into a property.
Here's the refactored code, which is now quite a bit shorter:

[source,python]
----
import math


class Vector(object):
    def __init__(self, value):
        self.angle = value

    @property
    def angle(self):
        return math.radians(self.angle_deg)

    @angle.setter
    def angle(self, value):
        self.angle_deg = math.degrees(value)


v = Vector(2 * math.pi)
print(v.angle)
print(v.angle_deg)

v.angle = math.pi
print(v.angle)
print(v.angle_deg)
----

This works just the same, as we see from the output:

[source,python]
----
6.283185307179586
360.0
3.141592653589793
180.0
----
